<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="pi" value="3.1415926535897931"/>

  <xacro:macro name="wheel" params="name parent *origin">
  <joint name="${name}_joint" type="continuous">
    <xacro:insert_block name="origin"/>
    <parent link="${parent}"/>
    <child link="${name}_link"/>
    <axis xyz="1 0 0"/>
  </joint>
  <link name="${name}_link">
    <visual>
      <geometry>
        <mesh filename="package://nucobot_description/pikea/meshes/wheel.dae"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://nucobot_description/pikea/meshes/wheel.dae"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0" 
               izz="0.001"/>
    </inertial>
  </link>
  <gazebo reference="${name}_link">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <minDepth>0.001</minDepth>
    <maxVel>1.0</maxVel>
  </gazebo>
  </xacro:macro>


  <xacro:macro name="diff_drive" params="name parent *origin wheelSeparation wheelDiameter">
  <!-- Wheel axis (fake link for easier coordinate transformation) -->
  <joint name="${name}_wheel_axis_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_wheel_axis_link"/>
  </joint>
  <link name="${name}_wheel_axis_link">
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0" 
               izz="0.001"/>
    </inertial>
  </link>
  
  <!-- Wheels -->
  <xacro:wheel name="${name}_wheel_left" parent="${name}_wheel_axis_link">
     <origin xyz="${ wheelSeparation/2} 0.0 0.0" rpy="${ pi/2} 0 0"/>
  </xacro:wheel>
  <xacro:wheel name="${name}_wheel_rght" parent="${name}_wheel_axis_link">
     <origin xyz="${-wheelSeparation/2} 0.0 0.0" rpy="${-pi/2} 0 0"/>
  </xacro:wheel>

  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>100</updateRate>
      <leftJoint> ${name}_wheel_rght_joint</leftJoint>
      <rightJoint>${name}_wheel_left_joint</rightJoint>
      <wheelSeparation>${wheelSeparation}</wheelSeparation>
      <wheelDiameter>${wheelDiameter}</wheelDiameter>
      <torque>20</torque>
      <wheelTorque>20</wheelTorque>
      <wheelAcceleration>0</wheelAcceleration>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <publishWheelTF>false</publishWheelTF>
      <publishWheelJointState>false</publishWheelJointState>
      <robotBaseFrame>${parent}</robotBaseFrame>
      <rosDebugLevel>na</rosDebugLevel>
    </plugin>
  </gazebo>
  </xacro:macro>
</robot>
